name: mokutil # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: mokutil snap # 79 char long summary
description: |
        Simple Snap for mokutil
        Mokutil is the utility to manipulate machines owner keys 
        which managed in shim

compression: lzo        
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
source-code: https://github.com/stulluk/mokutil-snap

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: autotools
    source: https://github.com/lcp/mokutil.git
    build-packages:
        - libssl-dev
        - libefivar-dev
        - libkeyutils-dev
        - pkg-config
    stage-packages:
        - libefivar1


apps: 
        mokutil:
                command: usr/local/bin/mokutil
                plugs: 
                - hardware-observe
